name: Lint and test

on:
  pull_request: {}

jobs:
  checks:
    name: Lint, typecheck, unit tests
    runs_on: linux-medium
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Unit tests
        run: npm run test
