-- NiX iOS product roadmap: private unread state, consented analytics,
-- share invites, activation, notification preferences, installations and exports.
-- Additive by design so older app binaries keep working.

-- ---------------------------------------------------------------------------
-- Private text conversation read state
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.conversation_read_states (
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  peer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  last_read_at TIMESTAMPTZ NOT NULL DEFAULT to_timestamp(0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, peer_id),
  CHECK (user_id <> peer_id)
);

ALTER TABLE public.conversation_read_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.conversation_read_states FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.conversation_read_states TO authenticated;

DROP POLICY IF EXISTS conversation_read_states_owner ON public.conversation_read_states;
CREATE POLICY conversation_read_states_owner ON public.conversation_read_states
  FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.mark_text_conversation_read(
  peer_id UUID,
  read_through TIMESTAMPTZ
)
RETURNS TIMESTAMPTZ
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id UUID := auth.uid();
  bounded_read_at TIMESTAMPTZ;
BEGIN
  IF actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF peer_id IS NULL OR peer_id = actor_id OR read_through IS NULL THEN
    RAISE EXCEPTION 'Invalid read state';
  END IF;

  SELECT LEAST(
    read_through,
    COALESCE(MAX(tm.created_at), to_timestamp(0))
  )
  INTO bounded_read_at
  FROM public.text_messages tm
  WHERE tm.sender_id = peer_id
    AND tm.receiver_id = actor_id
    AND tm.expires_at > now();

  INSERT INTO public.conversation_read_states(user_id, peer_id, last_read_at, updated_at)
  VALUES (actor_id, peer_id, bounded_read_at, now())
  ON CONFLICT (user_id, peer_id) DO UPDATE
  SET last_read_at = GREATEST(public.conversation_read_states.last_read_at, EXCLUDED.last_read_at),
      updated_at = now();

  RETURN bounded_read_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_unread_inbox_count_for_user(p_user_id UUID)
RETURNS INTEGER
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT LEAST(
    999,
    (
      SELECT COUNT(*)::INTEGER
      FROM public.nixes n
      WHERE n.receiver_id = p_user_id
        AND n.is_viewed IS NOT TRUE
        AND n.status = 'sent'
    ) + (
      SELECT COUNT(*)::INTEGER
      FROM public.text_messages tm
      LEFT JOIN public.conversation_read_states crs
        ON crs.user_id = p_user_id AND crs.peer_id = tm.sender_id
      WHERE tm.receiver_id = p_user_id
        AND tm.expires_at > now()
        AND tm.created_at > COALESCE(crs.last_read_at, to_timestamp(0))
    )
  );
$$;

CREATE OR REPLACE FUNCTION public.get_unread_inbox_count()
RETURNS INTEGER
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT public.get_unread_inbox_count_for_user(auth.uid());
$$;

REVOKE ALL ON FUNCTION public.mark_text_conversation_read(UUID, TIMESTAMPTZ) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_unread_inbox_count() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_unread_inbox_count_for_user(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mark_text_conversation_read(UUID, TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_unread_inbox_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_unread_inbox_count_for_user(UUID) TO service_role;

-- ---------------------------------------------------------------------------
-- Explicit-consent product analytics
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.product_analytics_preferences (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  policy_version TEXT NOT NULL DEFAULT '2026-07-29',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installation_id UUID NOT NULL,
  event_name TEXT NOT NULL CHECK (event_name IN (
    'onboarding_completed',
    'inbox_search_used',
    'invite_shared',
    'invite_opened',
    'invite_redeemed',
    'first_friend_accepted',
    'first_nix_sent',
    'nix_opened',
    'text_outbox_retry',
    'push_preference_changed',
    'data_export_requested'
  )),
  app_version TEXT,
  locale TEXT NOT NULL CHECK (locale IN ('pl', 'en')),
  properties JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (jsonb_typeof(properties) = 'object'),
  CHECK (octet_length(properties::TEXT) <= 2048)
);

CREATE INDEX IF NOT EXISTS product_analytics_events_created_idx
  ON public.product_analytics_events(created_at);
CREATE INDEX IF NOT EXISTS product_analytics_events_name_created_idx
  ON public.product_analytics_events(event_name, created_at);

CREATE TABLE IF NOT EXISTS public.product_analytics_daily (
  event_date DATE NOT NULL,
  event_name TEXT NOT NULL,
  locale TEXT NOT NULL,
  event_count BIGINT NOT NULL,
  PRIMARY KEY (event_date, event_name, locale)
);

ALTER TABLE public.product_analytics_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_analytics_daily ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.product_analytics_preferences FROM PUBLIC, anon;
REVOKE ALL ON TABLE public.product_analytics_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.product_analytics_daily FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.product_analytics_preferences TO authenticated;

DROP POLICY IF EXISTS product_analytics_preferences_owner ON public.product_analytics_preferences;
CREATE POLICY product_analytics_preferences_owner ON public.product_analytics_preferences
  FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.set_product_analytics_consent(p_enabled BOOLEAN)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  INSERT INTO public.product_analytics_preferences(user_id, enabled, policy_version, updated_at)
  VALUES (auth.uid(), COALESCE(p_enabled, FALSE), '2026-07-29', now())
  ON CONFLICT (user_id) DO UPDATE
  SET enabled = EXCLUDED.enabled,
      policy_version = EXCLUDED.policy_version,
      updated_at = now();
$$;

CREATE OR REPLACE FUNCTION public.record_product_analytics_event(
  p_installation_id UUID,
  p_event_name TEXT,
  p_app_version TEXT,
  p_locale TEXT,
  p_properties JSONB DEFAULT '{}'::JSONB
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL OR p_installation_id IS NULL THEN RETURN FALSE; END IF;
  IF NOT COALESCE((
    SELECT pref.enabled
    FROM public.product_analytics_preferences pref
    WHERE pref.user_id = auth.uid()
  ), FALSE) THEN
    RETURN FALSE;
  END IF;
  IF p_event_name NOT IN (
    'onboarding_completed', 'inbox_search_used', 'invite_shared', 'invite_opened',
    'invite_redeemed', 'first_friend_accepted', 'first_nix_sent', 'nix_opened',
    'text_outbox_retry', 'push_preference_changed', 'data_export_requested'
  ) THEN
    RAISE EXCEPTION 'Unsupported analytics event';
  END IF;
  IF lower(p_locale) NOT IN ('pl', 'en') THEN RAISE EXCEPTION 'Unsupported locale'; END IF;
  IF jsonb_typeof(COALESCE(p_properties, '{}'::JSONB)) <> 'object'
     OR octet_length(COALESCE(p_properties, '{}'::JSONB)::TEXT) > 2048 THEN
    RAISE EXCEPTION 'Invalid analytics properties';
  END IF;

  INSERT INTO public.product_analytics_events(
    installation_id, event_name, app_version, locale, properties
  )
  VALUES (
    p_installation_id,
    p_event_name,
    left(NULLIF(trim(p_app_version), ''), 40),
    lower(p_locale),
    COALESCE(p_properties, '{}'::JSONB)
  );
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.rollup_and_cleanup_product_analytics()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.product_analytics_daily(event_date, event_name, locale, event_count)
  SELECT created_at::DATE, event_name, locale, COUNT(*)
  FROM public.product_analytics_events
  WHERE created_at < date_trunc('day', now())
  GROUP BY created_at::DATE, event_name, locale
  ON CONFLICT (event_date, event_name, locale) DO UPDATE
  SET event_count = EXCLUDED.event_count;

  DELETE FROM public.product_analytics_events
  WHERE created_at < now() - INTERVAL '30 days';
END;
$$;

REVOKE ALL ON FUNCTION public.set_product_analytics_consent(BOOLEAN) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.record_product_analytics_event(UUID, TEXT, TEXT, TEXT, JSONB) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rollup_and_cleanup_product_analytics() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_product_analytics_consent(BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_product_analytics_event(UUID, TEXT, TEXT, TEXT, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rollup_and_cleanup_product_analytics() TO service_role;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule(jobid)
    FROM cron.job
    WHERE jobname = 'nix-product-analytics-cleanup';
    PERFORM cron.schedule(
      'nix-product-analytics-cleanup',
      '20 3 * * *',
      'SELECT public.rollup_and_cleanup_product_analytics();'
    );
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- Share invites and activation
-- ---------------------------------------------------------------------------

ALTER TABLE public.friend_invites
  DROP CONSTRAINT IF EXISTS friend_invites_channel_check;
ALTER TABLE public.friend_invites
  ADD CONSTRAINT friend_invites_channel_check CHECK (channel IN ('qr', 'share'));

CREATE OR REPLACE FUNCTION public.create_friend_invite(invite_channel TEXT)
RETURNS TABLE(invite_token TEXT, expires_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id UUID := auth.uid();
  normalized_channel TEXT := lower(trim(invite_channel));
  token_plain TEXT;
  token_digest TEXT;
  expiration TIMESTAMPTZ;
BEGIN
  IF actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF private.is_account_restricted(actor_id) THEN RAISE EXCEPTION 'Account is restricted'; END IF;
  IF normalized_channel NOT IN ('qr', 'share') THEN RAISE EXCEPTION 'Invalid invite channel'; END IF;

  token_plain := replace(extensions.gen_random_uuid()::TEXT, '-', '')
    || replace(extensions.gen_random_uuid()::TEXT, '-', '');
  token_digest := md5(token_plain);
  expiration := CASE normalized_channel
    WHEN 'share' THEN now() + INTERVAL '7 days'
    ELSE now() + INTERVAL '5 minutes'
  END;

  INSERT INTO public.friend_invites(created_by, token_hash, channel, expires_at)
  VALUES (actor_id, token_digest, normalized_channel, expiration);
  RETURN QUERY SELECT token_plain, expiration;
END;
$$;

CREATE TABLE IF NOT EXISTS public.user_activation_state (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  skipped_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_shown_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.user_activation_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.user_activation_state FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.user_activation_state TO authenticated;
DROP POLICY IF EXISTS user_activation_state_owner ON public.user_activation_state;
CREATE POLICY user_activation_state_owner ON public.user_activation_state
  FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.get_user_activation_state()
RETURNS TABLE(
  has_friend BOOLEAN,
  has_sent_nix BOOLEAN,
  skipped_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_shown_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id UUID := auth.uid();
  friend_exists BOOLEAN;
  nix_exists BOOLEAN;
  activation public.user_activation_state%ROWTYPE;
BEGIN
  IF actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  SELECT EXISTS (
    SELECT 1 FROM public.friendships f
    WHERE f.status = 'accepted'
      AND (f.user_id = actor_id OR f.friend_id = actor_id)
  ) INTO friend_exists;
  SELECT EXISTS (
    SELECT 1 FROM public.nixes n WHERE n.sender_id = actor_id
  ) INTO nix_exists;

  INSERT INTO public.user_activation_state(user_id, completed_at)
  VALUES (actor_id, CASE WHEN friend_exists AND nix_exists THEN now() ELSE NULL END)
  ON CONFLICT (user_id) DO UPDATE
  SET completed_at = CASE
        WHEN public.user_activation_state.completed_at IS NOT NULL
          THEN public.user_activation_state.completed_at
        WHEN friend_exists AND nix_exists THEN now()
        ELSE NULL
      END,
      updated_at = now()
  RETURNING * INTO activation;

  RETURN QUERY SELECT friend_exists, nix_exists, activation.skipped_at,
    activation.dismissed_at, activation.completed_at, activation.last_shown_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_user_activation_state(
  p_action TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF p_action NOT IN ('shown', 'skip', 'dismiss') THEN RAISE EXCEPTION 'Invalid activation action'; END IF;
  INSERT INTO public.user_activation_state(
    user_id, skipped_at, dismissed_at, last_shown_at, updated_at
  )
  VALUES (
    auth.uid(),
    CASE WHEN p_action = 'skip' THEN now() ELSE NULL END,
    CASE WHEN p_action = 'dismiss' THEN now() ELSE NULL END,
    CASE WHEN p_action = 'shown' THEN now() ELSE NULL END,
    now()
  )
  ON CONFLICT (user_id) DO UPDATE
  SET skipped_at = CASE WHEN p_action = 'skip' THEN now() ELSE public.user_activation_state.skipped_at END,
      dismissed_at = CASE WHEN p_action = 'dismiss' THEN now() ELSE public.user_activation_state.dismissed_at END,
      last_shown_at = CASE WHEN p_action = 'shown' THEN now() ELSE public.user_activation_state.last_shown_at END,
      updated_at = now();
END;
$$;

REVOKE ALL ON FUNCTION public.get_user_activation_state() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.update_user_activation_state(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_activation_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_activation_state(TEXT) TO authenticated;

-- ---------------------------------------------------------------------------
-- Notification preferences and per-conversation mute
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  messages_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  reactions_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  friends_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversation_mutes (
  owner_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  peer_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  muted_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_user_id, peer_user_id),
  CHECK (owner_user_id <> peer_user_id)
);

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_mutes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.notification_preferences, public.conversation_mutes FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.notification_preferences TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.conversation_mutes TO authenticated;

DROP POLICY IF EXISTS notification_preferences_owner ON public.notification_preferences;
CREATE POLICY notification_preferences_owner ON public.notification_preferences
  FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS conversation_mutes_owner ON public.conversation_mutes;
CREATE POLICY conversation_mutes_owner ON public.conversation_mutes
  FOR ALL TO authenticated
  USING (owner_user_id = auth.uid())
  WITH CHECK (owner_user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.set_notification_preferences(
  p_messages_enabled BOOLEAN,
  p_reactions_enabled BOOLEAN,
  p_friends_enabled BOOLEAN
)
RETURNS public.notification_preferences
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE result public.notification_preferences;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  INSERT INTO public.notification_preferences(
    user_id, messages_enabled, reactions_enabled, friends_enabled, updated_at
  )
  VALUES (
    auth.uid(), COALESCE(p_messages_enabled, TRUE), COALESCE(p_reactions_enabled, TRUE),
    COALESCE(p_friends_enabled, TRUE), now()
  )
  ON CONFLICT (user_id) DO UPDATE SET
    messages_enabled = EXCLUDED.messages_enabled,
    reactions_enabled = EXCLUDED.reactions_enabled,
    friends_enabled = EXCLUDED.friends_enabled,
    updated_at = now()
  RETURNING * INTO result;
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_conversation_mute(
  p_peer_id UUID,
  p_muted_until TIMESTAMPTZ,
  p_indefinite BOOLEAN DEFAULT FALSE
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF p_peer_id IS NULL OR p_peer_id = auth.uid() THEN RAISE EXCEPTION 'Invalid peer'; END IF;
  IF NOT p_indefinite AND (p_muted_until IS NULL OR p_muted_until <= now()) THEN
    DELETE FROM public.conversation_mutes
    WHERE owner_user_id = auth.uid() AND peer_user_id = p_peer_id;
    RETURN;
  END IF;
  INSERT INTO public.conversation_mutes(owner_user_id, peer_user_id, muted_until, updated_at)
  VALUES (auth.uid(), p_peer_id, CASE WHEN p_indefinite THEN NULL ELSE p_muted_until END, now())
  ON CONFLICT (owner_user_id, peer_user_id) DO UPDATE
  SET muted_until = EXCLUDED.muted_until, updated_at = now();
END;
$$;

REVOKE ALL ON FUNCTION public.set_notification_preferences(BOOLEAN, BOOLEAN, BOOLEAN) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_conversation_mute(UUID, TIMESTAMPTZ, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_notification_preferences(BOOLEAN, BOOLEAN, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_conversation_mute(UUID, TIMESTAMPTZ, BOOLEAN) TO authenticated;

-- ---------------------------------------------------------------------------
-- Authenticated installations and account data exports
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.app_installations (
  installation_id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  device_name TEXT NOT NULL,
  system_version TEXT,
  app_version TEXT,
  locale TEXT NOT NULL CHECK (locale IN ('pl', 'en')),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS app_installations_user_seen_idx
  ON public.app_installations(user_id, last_seen_at DESC);

ALTER TABLE public.app_installations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.app_installations FROM PUBLIC, anon;
GRANT SELECT ON TABLE public.app_installations TO authenticated;
DROP POLICY IF EXISTS app_installations_owner_select ON public.app_installations;
CREATE POLICY app_installations_owner_select ON public.app_installations
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.register_app_installation(
  p_installation_id UUID,
  p_device_name TEXT,
  p_system_version TEXT,
  p_app_version TEXT,
  p_locale TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL OR p_installation_id IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  INSERT INTO public.app_installations(
    installation_id, user_id, device_name, system_version, app_version, locale,
    last_seen_at, revoked_at, updated_at
  )
  VALUES (
    p_installation_id, auth.uid(), left(COALESCE(NULLIF(trim(p_device_name), ''), 'iPhone'), 100),
    left(NULLIF(trim(p_system_version), ''), 40), left(NULLIF(trim(p_app_version), ''), 40),
    CASE WHEN lower(p_locale) = 'pl' THEN 'pl' ELSE 'en' END,
    now(), NULL, now()
  )
  ON CONFLICT (installation_id) DO UPDATE SET
    user_id = auth.uid(),
    device_name = EXCLUDED.device_name,
    system_version = EXCLUDED.system_version,
    app_version = EXCLUDED.app_version,
    locale = EXCLUDED.locale,
    last_seen_at = now(),
    revoked_at = NULL,
    updated_at = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_other_app_installations(p_current_installation_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE affected INTEGER;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  UPDATE public.app_installations
  SET revoked_at = now(), updated_at = now()
  WHERE user_id = auth.uid()
    AND installation_id <> p_current_installation_id
    AND revoked_at IS NULL;
  GET DIAGNOSTICS affected = ROW_COUNT;

  UPDATE public.push_devices
  SET enabled = FALSE, disabled_reason = 'other_sessions_signed_out', updated_at = now()
  WHERE user_id = auth.uid() AND installation_id <> p_current_installation_id;
  RETURN affected;
END;
$$;

REVOKE ALL ON FUNCTION public.register_app_installation(UUID, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.revoke_other_app_installations(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.register_app_installation(UUID, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_other_app_installations(UUID) TO authenticated;

CREATE TABLE IF NOT EXISTS public.data_export_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'processing', 'ready', 'failed', 'expired')),
  storage_path TEXT,
  archive_size_bytes BIGINT,
  manifest_sha256 TEXT,
  error_code TEXT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS data_export_jobs_user_requested_idx
  ON public.data_export_jobs(user_id, requested_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS data_export_jobs_one_active_idx
  ON public.data_export_jobs(user_id)
  WHERE status IN ('queued', 'processing');

ALTER TABLE public.data_export_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.data_export_jobs FROM PUBLIC, anon;
GRANT SELECT ON TABLE public.data_export_jobs TO authenticated;
DROP POLICY IF EXISTS data_export_jobs_owner_select ON public.data_export_jobs;
CREATE POLICY data_export_jobs_owner_select ON public.data_export_jobs
  FOR SELECT TO authenticated USING (user_id = auth.uid());

INSERT INTO storage.buckets(id, name, public, file_size_limit)
VALUES ('account-exports', 'account-exports', FALSE, 1073741824)
ON CONFLICT (id) DO UPDATE SET public = FALSE;

CREATE OR REPLACE FUNCTION public.request_data_export()
RETURNS public.data_export_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE result public.data_export_jobs;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF EXISTS (
    SELECT 1 FROM public.data_export_jobs j
    WHERE j.user_id = auth.uid()
      AND (
        j.status IN ('queued', 'processing')
        OR j.requested_at > now() - INTERVAL '24 hours'
      )
  ) THEN
    RAISE EXCEPTION 'Data export is already active or was requested recently';
  END IF;
  INSERT INTO public.data_export_jobs(user_id)
  VALUES (auth.uid())
  RETURNING * INTO result;
  RETURN result;
END;
$$;

REVOKE ALL ON FUNCTION public.request_data_export() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.request_data_export() TO authenticated;

CREATE OR REPLACE FUNCTION public.cleanup_expired_data_exports()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.data_export_jobs
  SET status = 'expired', updated_at = now()
  WHERE status = 'ready' AND expires_at <= now();
  DELETE FROM public.data_export_jobs
  WHERE requested_at < now() - INTERVAL '30 days';
END;
$$;

REVOKE ALL ON FUNCTION public.cleanup_expired_data_exports() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_data_exports() TO service_role;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule(jobid)
    FROM cron.job
    WHERE jobname = 'nix-data-export-cleanup';
    PERFORM cron.schedule(
      'nix-data-export-cleanup',
      '40 3 * * *',
      'SELECT public.cleanup_expired_data_exports();'
    );
  END IF;
END
$$;
